import { jsPDF } from "jspdf";
import type { ProposalProject } from "@/lib/api";

function section(doc: jsPDF, title: string, content: string, y: number) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(title, 14, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const lines = doc.splitTextToSize(content || "Not provided.", 182);
  doc.text(lines, 14, y + 6);

  return y + 10 + lines.length * 5;
}

export function exportProjectToPdf(project: ProposalProject) {
  const doc = new jsPDF();
  let y = 16;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(project.project_name || "Proposal", 14, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Client: ${project.client_name || "-"}`, 14, y);
  y += 5;
  doc.text(`Type: ${project.project_type || "-"}`, 14, y);
  y += 5;
  doc.text(`Budget: ${project.budget || "-"}`, 14, y);
  y += 5;
  doc.text(`Timeline: ${project.timeline || "-"}`, 14, y);
  y += 8;

  y = section(doc, "Summary", project.summary, y);
  y = section(doc, "Scope", project.scope, y);
  y = section(doc, "Deliverables", project.deliverables, y);
  y = section(doc, "Milestones", project.milestones, y);
  y = section(doc, "Risks", project.risks, y);

  if (y > 270) {
    doc.addPage();
    y = 16;
  }

  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(`Generated by ScopeFlow AI on ${new Date().toLocaleString()}`, 14, 285);

  const safeName = (project.project_name || "proposal").replace(/[^\w-]+/g, "_");
  doc.save(`${safeName}.pdf`);
}
