import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import PDFDocument from "pdfkit";

export type ExportSections = {
  summary: string[];
  scope_of_work: string[];
  deliverables: string[];
  milestones: Array<{ title: string; description: string }>;
  timeline: string[];
  pricing: string[];
  risks: string[];
  next_steps: string[];
};

function filenamePart(value: string, fallback: string) {
  return value.trim().toLowerCase().replace(/[^a-z0-9_-]+/g, "-").replace(/^-+|-+$/g, "") || fallback;
}

export function buildExportFilename(projectName: string, sourceLabel: string, extension: string) {
  const date = new Date().toISOString().slice(0, 10).replaceAll("-", "");
  return `${filenamePart(projectName, "proposal")}-${filenamePart(sourceLabel, "current")}-${date}.${extension}`;
}

function paragraphs(value: string): string[] {
  if (!value.trim()) return ["Not provided."];
  return value.split(/\r?\n\s*\r?\n/).map((part) => part.split(/\r?\n/).map((line) => line.trim()).filter(Boolean).join(" ")).filter(Boolean);
}

function listItems(value: string): string[] {
  if (!value.trim()) return ["Not provided."];
  const items = value.split(/\r?\n/).map((line) => line.trim().replace(/^[-*\u2022]\s*/, "").replace(/^\d+[.)]\s*/, "").trim()).filter(Boolean);
  return items.length ? items : ["Not provided."];
}

function milestoneItems(value: string) {
  if (!value.trim()) return [{ title: "Milestone", description: "Not provided." }];
  const items = value.split(/\r?\n/).map((line) => line.trim().replace(/^[-*\u2022]\s*/, "")).filter(Boolean).map((line) => {
    const separator = line.indexOf(":");
    return separator >= 0
      ? { title: line.slice(0, separator).trim() || "Milestone", description: line.slice(separator + 1).trim() || "Not provided." }
      : { title: "Milestone", description: line };
  });
  return items.length ? items : [{ title: "Milestone", description: "Not provided." }];
}

export function buildExportSections(source: {
  summary: string; scope: string; deliverables: string; milestones: string;
  proposalTimeline: string; pricing: string; risks: string; nextSteps: string;
}): ExportSections {
  return {
    summary: paragraphs(source.summary),
    scope_of_work: listItems(source.scope),
    deliverables: listItems(source.deliverables),
    milestones: milestoneItems(source.milestones),
    timeline: listItems(source.proposalTimeline),
    pricing: listItems(source.pricing),
    risks: listItems(source.risks),
    next_steps: listItems(source.nextSteps)
  };
}

type ExportMetadata = {
  projectName: string;
  clientName: string;
  projectType: string;
  budget: string;
  timeline: string;
  sourceLabel: string;
};

function metadataLines(metadata: ExportMetadata) {
  return [
    ["Client", metadata.clientName || "-"],
    ["Project Type", metadata.projectType || "-"],
    ["Budget", metadata.budget || "-"],
    ["Timeline", metadata.timeline || "-"],
    ["Export Source", metadata.sourceLabel]
  ] as const;
}

function bulletParagraph(text: string) {
  return new Paragraph({ text, bullet: { level: 0 } });
}

export async function generateDocx(metadata: ExportMetadata, sections: ExportSections): Promise<Buffer> {
  const children: Paragraph[] = [
    new Paragraph({ text: metadata.projectName || "Proposal", heading: HeadingLevel.TITLE }),
    ...metadataLines(metadata).map(([label, value]) => new Paragraph({ children: [new TextRun({ text: `${label}: `, bold: true }), new TextRun(value)] })),
    new Paragraph("")
  ];
  const add = (title: string, body: Paragraph[]) => children.push(new Paragraph({ text: title, heading: HeadingLevel.HEADING_1 }), ...body);
  add("Summary", sections.summary.map((text) => new Paragraph(text)));
  add("Scope of Work", sections.scope_of_work.map(bulletParagraph));
  add("Deliverables", sections.deliverables.map(bulletParagraph));
  add("Milestones", sections.milestones.map((item) => new Paragraph({ bullet: { level: 0 }, children: [new TextRun({ text: `${item.title}: `, bold: true }), new TextRun(item.description)] })));
  add("Timeline", sections.timeline.map(bulletParagraph));
  add("Pricing", sections.pricing.map(bulletParagraph));
  add("Risks", sections.risks.map(bulletParagraph));
  add("Next Steps", sections.next_steps.map(bulletParagraph));
  children.push(new Paragraph(""), new Paragraph(`Generated by ScopeFlow AI on ${new Date().toISOString().slice(0, 19).replace("T", " ")}`));
  const document = new Document({ sections: [{ children }] });
  return Packer.toBuffer(document);
}

export function generatePdf(metadata: ExportMetadata, sections: ExportSections): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const document = new PDFDocument({ size: "LETTER", margins: { top: 50, right: 50, bottom: 50, left: 50 }, info: { Title: metadata.projectName || "Proposal" } });
    const chunks: Buffer[] = [];
    document.on("data", (chunk: Buffer) => chunks.push(chunk));
    document.on("end", () => resolve(Buffer.concat(chunks)));
    document.on("error", reject);
    document.font("Helvetica-Bold").fontSize(20).fillColor("#0f172a").text(metadata.projectName || "Proposal").moveDown(0.5);
    document.fontSize(10.5).fillColor("#374151");
    for (const [label, value] of metadataLines(metadata)) {
      document.font("Helvetica-Bold").text(`${label}: `, { continued: true }).font("Helvetica").text(value);
    }
    const heading = (title: string) => document.moveDown(0.8).font("Helvetica-Bold").fontSize(13).fillColor("#111827").text(title).moveDown(0.25);
    const body = (text: string, bullet = false) => document.font("Helvetica").fontSize(10.5).fillColor("#1f2937").text(bullet ? `- ${text}` : text, { indent: bullet ? 12 : 0, lineGap: 3 });
    heading("Summary"); sections.summary.forEach((item) => body(item));
    heading("Scope of Work"); sections.scope_of_work.forEach((item) => body(item, true));
    heading("Deliverables"); sections.deliverables.forEach((item) => body(item, true));
    heading("Milestones"); sections.milestones.forEach((item) => body(`${item.title}: ${item.description}`, true));
    heading("Timeline"); sections.timeline.forEach((item) => body(item, true));
    heading("Pricing"); sections.pricing.forEach((item) => body(item, true));
    heading("Risks"); sections.risks.forEach((item) => body(item, true));
    heading("Next Steps"); sections.next_steps.forEach((item) => body(item, true));
    document.moveDown().fontSize(9).fillColor("#6b7280").text(`Generated by ScopeFlow AI on ${new Date().toISOString().slice(0, 19).replace("T", " ")}`);
    document.end();
  });
}
