# Generated by Django 6.0.3 on 2026-03-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=100)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('requirements', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('milestones', models.TextField(blank=True)),
                ('risks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
