# Generated by Django 6.0.3 on 2026-03-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalproject',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='missing_information',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='scope_risks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='suggested_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='unclear_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='proposalproject',
            name='budget',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='proposalproject',
            name='project_type',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='proposalproject',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proposalproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('completed', 'Completed')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='proposalproject',
            name='timeline',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
