# Generated by Django 6.0.3 on 2026-04-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0002_alter_proposalproject_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("label", models.CharField(max_length=50)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("generate", "Generate"),
                            ("regenerate", "Regenerate"),
                            ("final", "Final"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("changed_sections", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True)),
                ("scope", models.TextField(blank=True)),
                ("deliverables", models.TextField(blank=True)),
                ("milestones", models.TextField(blank=True)),
                ("risks", models.TextField(blank=True)),
                ("is_final", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="proposals.proposalproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="proposalproject",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="proposals.proposalversion",
            ),
        ),
    ]
