# Generated by Django 6.0.3 on 2026-04-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposalversion_proposalproject_current_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalproject',
            name='generated_proposal',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
