# Generated by Django 6.0.3 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0004_proposalproject_generated_proposal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposalproject",
            name="user_id",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="proposalproject",
            index=models.Index(fields=["user_id", "updated_at"], name="proposal_user_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="proposalversion",
            index=models.Index(fields=["project", "is_final", "created_at"], name="proposal_ver_export_idx"),
        ),
    ]
