# Generated by Django 6.0.3 on 2026-05-27 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_userplan_usagerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalproject',
            name='next_steps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='pricing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='proposal_timeline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='next_steps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='pricing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='proposal_timeline',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AIPromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=50)),
                ('purpose', models.CharField(choices=[('full_proposal', 'Full Proposal'), ('section_regeneration', 'Section Regeneration'), ('quality_review', 'Quality Review'), ('edit_suggestions', 'Edit Suggestions')], db_index=True, max_length=50)),
                ('prompt_text', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['purpose', '-is_active', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('purpose', 'version'), name='unique_prompt_purpose_version')],
            },
        ),
        migrations.CreateModel(
            name='AIQualityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('summary', models.TextField()),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reviews', to='proposals.proposalproject')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_reviews', to='proposals.aipromptversion')),
                ('proposal_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_reviews', to='proposals.proposalversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='ai_review_project_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('full_proposal_generation', 'Full Proposal Generation'), ('section_regeneration', 'Section Regeneration'), ('quality_score', 'Quality Score'), ('edit_suggestions', 'Edit Suggestions')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], db_index=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='proposals.proposalproject')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='proposals.aipromptversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_usage_user_created_idx'), models.Index(fields=['action_type', 'created_at'], name='ai_usage_action_created_idx')],
            },
        ),
    ]
