# Generated by Django 6.0.3 on 2026-06-06 08:48

import django.db.models.deletion
from django.db import migrations, models


def normalize_legacy_statuses(apps, schema_editor):
    ProposalProject = apps.get_model("proposals", "ProposalProject")
    ProposalProject.objects.filter(status__in=["in_review", "completed"]).update(status="draft")
    ProposalProject.objects.filter(user_id__startswith="demo-seed-").update(is_demo=True)


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_proposalproject_next_steps_proposalproject_pricing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalproject',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='client_email_response',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='client_name_response',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='client_response_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='share_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='share_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='share_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proposalproject',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(normalize_legacy_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='proposalproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=50),
        ),
        migrations.CreateModel(
            name='ProposalClientComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_comments', to='proposals.proposalproject')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
